libzen-compositor/virtual-object.c, zen-shell/cuboid-window.c
roleがない状態のvirtual_objectのrole属性をNULL → 空文字にした。
roleがないvirtual object もrole があるvirtual object 同様に strcmp によって、roleチェックができるように。
=> use "" for the initial role name

clients/simple-box/box.cc, zen-renderer/opengl/opengl-renderer.c
alpha testを行うようにした。
これによって a = 0 の部分は描画されない。
これがないとzwaylandのカーソルの周りに四角い枠がついたりしてしまう
=> alpha test

clients/include/zukou.h, clients/simple-box/box.cc, clients/simple-box/box.h, clients/zukou/glm-helper.cc, clients/zukou/opengl-shader-program.cc, zen-renderer/opengl/opengl-component.c, zen-renderer/opengl/opengl-shader-program.c, zen-renderer/opengl/opengl-shader-program.h
https://github.com/zigen-project/zigen/pull/14
↑ これを使って uniform 変数をクライアント側から渡せるようにした。
box の 回転情報を uniform変数で渡して、GPU内でrotationの計算をするようにした。
https://github.com/zigen-project/zigen/pull/14 をマージしないとtestが通らない
#13 とコンフリクトする可能性が高い
=> uniform variable

include/libzen-compositor/libzen-compositor.h, libzen-compositor/keyboard.c, libzen-compositor/seat.c
modifiersを送るようにした
これにより
- weston-terminalやchromeで、大文字や記号、「ctl + c」とかは使える
- chromeのショートカットキーは使えない
https://github.com/zigen-project/zwayland/pull/18
https://github.com/zigen-project/zsurface/pull/16
=> Add keyboard modifiers

include/libzen-compositor/libzen-compositor.h, libzen-compositor/config.c, tests/load-backend.c, zen-backend/glfw/output.c, zen-backend/openvr/gl-window.cc, zen-backend/openvr/gl-window.h, zen-backend/openvr/output.cc, zen/main.c
デモやる時とか、zenのpreview見てる時も、glfwのwindow上にマウスカーソルがあるの邪魔だな & 混乱を招くなと思ったのでこのPR。
Ubuntu Desktopのwindowを閉じるmenu barのバツとかを押す時はカーソルが表示される。
逆にcursorを表示させたいケースが思い浮かばなかったのでoptionにはしてません。
=> Hide cursor on glfw window

libzen-compositor/virtual-object.c, zen-shell/shell.c
** merge into main**
cuboid windowの初期位置を、大きいobjectは奥に、小さいオブジェクトは手前になるようにした。
初期位置で自信が覆われてしまうことがなくなる。
=> Adjust initial cuboid window position

zen-backend/openvr/hmd.cc, zen-renderer/opengl/cuboid-window-render-item.c
**merge into demo**
3点修正しました。
- cuboid window の枠をfocusが当たってない時は出さない
- better preview の視野角をy方向に-3° ずらした
- cuboid_windwo.movedイベントから送られる視線方向のvec3がずれてて、zmonitorsとかがちゃんとこっち向かない問題を解消。
=> fix for demo

zen-renderer/opengl/opengl-shader-program.c
OpenGLのエラーが512文字を超えるとzenが落ちてしまう問題を見つけたので解決
=> Fix opengl error max size

.github/workflows/test.yaml, README.adoc, meson.build, src/main.c, src/meson.build, zen.desktop
- add `-s` `--startup-command` option
- specify the startup command which is executed on startup
- when the process of the startup command terminated, the display server will also be terminated
- Enable to start zen from window managers
- with startup command `weston-terminal`
=> start from window manager

include/zen/scene/view.h, include/zen/xwayland-view.h, zen/meson.build, zen/output.c, zen/server.c, zen/xwayland-view.c
Add Xwayland support for drawing only.
X clients such as steam and steamvr cannot be rendered yet, so I will create an additional PR for those support.
=> Add Xwayland support for drawing only

cui-client/main.c, cui-client/meson.build, include/zen/display-system.h, meson.build, meson_options.txt, protocols/meson.build, zen/display-system.c, zen/meson.build, zen/server.c
- handle zen_display_system switch request, and just return zen_display_system_applied event.
- refactor build system regarding protocols
- I created a client, and the current build system does not work well with building clients. 
- create a CUI client that send requests and receive events regarding zen_display_system.
- This client application are to be remove when corresponding GUI application is developed
1. start `zen-desktop`
2. start a CUI client
```
$ ./build/cui-client/zen-desktop-cui-client
```
3. start another client in another shell
```
$ ./build/cui-client/zen-desktop-cui-client
```
4. enter a command, "screen" or "immersive" in a client
The client send zen_display_system::switch_type request with type argument, then both clients will receive zen_display_system::applied …
=> Handle display system switch protocol

meson.build
#74 
Remove prefix from `__FILE__` macro with a compiler option.
See `-fmacro-prefix-map` in the [gcc doumentation](https://gcc.gnu.org/onlinedocs/gcc/Preprocessor-Options.html). In [the sway change I referred to](https://github.com/swaywm/sway/commit/2dc4978d8af326c310057ca8fd22a4c7f5d09335), it also handles the cases when the option is not available. However, the change adds another macro and complicates the program, and the option has been available for a long time (from gcc8 and clang10), so I decided to just ignore such a case.
I bulit `zen-desktop`, ran it, and saw the following output as the log.
```
00:00:00.026 [zen/server.c:255] WAYLAND_DISPLAY=wayland-1
00:00:00.026 [zen/server.c:256] XDG_RUNTIME_DIR=/run/user/1000
00:00:00.026 [zen/server.c:153] DISPLAY=:2
```
=> Remove relative path prefix from __FILE__

.github/workflows/test.yaml, common/include/zen-common/util.h, cui-client/main.c, immersive-backend/include/zen-immersive-backend.h, immersive-backend/meson.build, immersive-backend/openvr/immersive-backend.cc, immersive-backend/openvr/meson.build, immersive-backend/openvr/vr-system.cc, immersive-backend/openvr/vr-system.h, include/zen/display-system.h, include/zen/server.h, meson.build, protocols/zen-desktop.xml, zen/display-system.c, zen/meson.build, zen/server.c
See #78
> create openvr backend as the first option of "immersive backend", and check if immersive display system is now available or not when a client request server to switch display system to "immersive".
- add concept of immersive backend, which handles immersive devices like HMD.
- create openvr immersive backend as the first option of "immersive backend", and check if immersive display system is now available or not when a client request server to switch display system to "immersive".
1. build
2. start zen-desktop without startup command. In its log, DISPLAY environment variable to use is printed.
3. start alvr
```
$ DISPLAY=:0 alvr_launcher
```
4. start cui-client (see #76 for detail)
5. enter "immersive" command in the cui client.
6. you will soon receive applied event if steamvr …
=> Immersive backend

README.adoc, include/zen/input-device.h, include/zen/seat.h, include/zen/server.h, zen/input-device.c, zen/keyboard.c, zen/main.c, zen/seat.c, zen/server.c
See #83 
Destroy zn_input_device before zn_seat
Exit more gracefully when key input is detected. If just  terminate with `exit(0)`, developers cannot know the termination process works well or not.
Exit with only Q key pressed. I want to use some key to switch keyboard between multiple computers.
1. build
2. start `zen-desktop`
3. press 'q'
You'll see `[zen/main.c:195] Exited gracefully` at the end of the log.
=> Exit normally

include/zen/server.h, meson.build, zen/server.c
See https://github.com/zigen-project/zen/pull/94#pullrequestreview-1057041890
Add compiler parameter that forbidden function declaration/definition with empty parentheses.
**bad (compile error)**
```
void func();
```
**good**
```
void func(void);
```
Compile with some empty parentheses function, and you will get compile error.
=> add -Wstrict-prototypes

include/zen/pointer.h, include/zen/scene/screen.h, include/zen/scene/view.h, include/zen/xdg-toplevel-view.h, include/zen/xwayland-view.h, zen/pointer.c, zen/render-2d.c, zen/scene/screen.c, zen/scene/view.c, zen/xdg-toplevel-view.c, zen/xwayland-view.c
implement a part of #89 
Give position information to each views, and send enter/leave/motion/axis event from pointer to client.
1. start zen with -s option
- `weston-clickdot` is recommended for testing `motion` event
- `weston-cliptest` is recommended for testing `axis` event
3. move the cursor or scroll on view
4. events are sended
=> Send pointer event

immersive-backend/include/zen-immersive-backend.h, immersive-backend/openvr/immersive-backend.cc, immersive-backend/openvr/meson.build, immersive-backend/openvr/vr-system.cc, immersive-backend/openvr/vr-system.h, include/zen/server.h, zen/server.c
See #78 
Integrate OpenVR's rendering and event loop with wayland's loop.
The wayland loop is event driven, epoll base loop.
OpenVR's loop with `vr::IVRCompositor::WaitGetPose` is blocking, synchronous loop like this.
```c
while(true){
HmdPose pose = compositor->WaitGetPose(); // block until next frame timing
event = compositor->PollNextEvent();
process_event(event);
texture_left_eye, texture_right_eye = render_with_pose(pose);
compositor->Submit(texture_left_eye, texture_right_eye);
}
```
This is the design diagram I implemented here. Actual rendering and submitting the rendered texture to OpenVR are out of this PR's scope.
1. Build
2. Start zen-desktop without startup command.
3. Start alvr and confirm that the alvr works with your HMD.
4. Start cui-client
Enter "immersive" command in …
=> repaint loop with openvr

.github/workflows/test.yaml, README.adoc, include/zen/binding.h, include/zen/input-manager.h, include/zen/keyboard.h, meson.build, zen/binding.c, zen/input-device.c, zen/input-manager.c, zen/keyboard.c, zen/main.c, zen/meson.build
Keyboard shortcut is short-hand way to check GUI shell functionalities we will implement from now on (switching focus, moving between virtual desktop, etc.).
So I implemented keyboard shortcut basis first.
Developers can add keyboard shortcut using
```c
struct zn_binding* zn_input_manager_add_key_binding(
struct zn_input_manager* self, uint32_t key, uint32_t modifiers,
zn_key_binding_handler_t handler, void* data);
```
`key` and `modifiers` are shortcut bindings to be used.
When `key` is pressed with `modifiers`, `handler` will be called with `data` in its argument.
See `main.c` for example.
1. build
2. start `zen-desktop`
3. press `<alt> + q`
zen-desktop will be terminated gracefully.
4. (option) try to create another keyboard shortcut.
Termination shortcut is changed to `<alt> + q`
=> key binding

include/zen/cursor.h, include/zen/scene/screen.h, include/zen/seat.h, zen/cursor.c, zen/output.c, zen/pointer.c, zen/render-2d.c, zen/scene/screen.c, zen/seat.c
In other DE, the cursor's appearance is changed when move cursor on view such as resize cursor. But zen can't.
Listening wlr_seat's `request_set_cursor` event.
1. start zen with -s option (`weston-dnd` is recommended)
2. move the cursor to corners of view or object in view
3. cursor's appearance will be changed
=> Set cursor surface

zen/seat.c
Bug fix.
When starting X client, the compositor crushes.
Fixed the bug.
Same as https://github.com/zigen-project/zen/pull/107.
=> handle when focus_surface is NULL

.github/workflows/test.yaml, README.adoc, meson.build, zen/meson.build, zen/server.c
[wlroots](https://gitlab.freedesktop.org/wlroots/wlroots) uses GLES2 for OpenGL-based renderer. We want to use the newer OpenGL extenstion functionalities, so I created a GLEW renderer with a similar API to the existing GLES2 renderer.
Repository: [zigen-project/wlr-glew-renderer
](https://github.com/zigen-project/wlr-glew-renderer)
This pull request integrate the GLEW renderer.
Nothing changed in this pull request.
=> use wlr-glew-renderer

include/zen/cursor.h, zen/cursor.c
When the cursor's surface is NULL, default texture is used on rendering, but it use wrong hotspot.
Set default hotspot when the cursor's surface is NULL.
None
=> Use default hotspot

include/zen/output.h, zen/output.c, zen/scene/screen.c
#136 
1. Check that views stay displayed when switching board.
2. build
3. start `zen-desktop` 
4. Check that views do not stay displayed when switching board.
=> damage whole screen when switching board

.github/workflows/lint.yaml, .github/workflows/test.yaml
We rename `dev` branch to `main` and set it default branch.
We should update CI settings.
none
=> remove dev branch from CI

zen/scene/screen.c
Now an error occurs when removing output.
```
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7e37622 in wlr_output_transformed_resolution (output=0x555000dc914b, width=0x7fffffffd320, height=0x7fffffffd324) at ../types/output/output.c:466
466		if (output->transform % 2 == 0) {
#0  0x00007ffff7e37622 in wlr_output_transformed_resolution (output=0x555000dc914b, width=0x7fffffffd320, height=0x7fffffffd324) at ../types/output/output.c:466
#1  0x00007ffff7e6132d in wlr_output_damage_add_whole (output_damage=0x55555594b500) at ../types/wlr_output_damage.c:199
#2  0x000055555555e029 in wl_signal_emit (data=0x7fffffffd340, signal=0x5555556dee98) at /usr/include/wayland-server-core.h:481
#3  zn_board_assign_to_screen (self=0x5555556dee30, screen=<optimized out>) at …
```
=> handle output disconnection

zen/scene/view.c
#125
When a new view is mapped to the scene with `zn_view_map_to_scene`, insert the view to the tail of the `view_list` so that the newest view is shown on the top of the view stack.
Run
```
zen-desktop -c weston-terminal
WAYLAND_DISPLAY=wayland-1 weston-flower
```
and confirm that the weston-flower client is shown on top of the terrminal.
=> insert new views to the tail of the view_list

zen/cursor.c
DRM headers seem to be located in different paths depending on the developers' environment.
I, at least, confirmed two locations.
- /usr/include/libdrm
- /usr/include/drm
`pkgconfig` absorb the difference by setting the Cflags `-I/usr/include/libdrm` or `-I/usr/include/drm`, so we should not do
```c
#include <libdrm/drm.h>
```
instead, do
```c
#include <drm.h>
```
No change
=> fix header include

zen/scene/view.c
See #122
`zn_view_damage()` fetches damage by `wlr_surface_get_effective_damage()`, and apply it.
start zen with some client, check that the view is rendered correctly.
=> handle damage to the view

common/include/zen-common.h, common/include/zen-common/log.h, common/include/zen-common/timespec-util.h, common/include/zen-common/util.h, include/zen/backend/immersive.h, include/zen/binding.h, include/zen/cursor.h, include/zen/display-system.h, include/zen/input/cursor-grab-move.h, include/zen/input/cursor-grab.h, include/zen/input/input-device.h, include/zen/input/input-manager.h, include/zen/input/keyboard.h, include/zen/input/pointer.h, include/zen/input/seat.h, include/zen/output.h, include/zen/scene/board.h, include/zen/scene/scene.h, include/zen/scene/screen-layout.h, include/zen/scene/screen.h, include/zen/scene/view.h, include/zen/screen-renderer.h, include/zen/server.h, include/zen/wlr/box.h, include/zen/xdg-toplevel-view.h, include/zen/xwayland-view.h, tests/test-runner.h, zen/backend/openvr/vr-system.h
- The existing include guard method is cumbersome and can result in duplicate #define strings due to programmer error.
- Replace the method(using `#ifndef`, `#define`, `#endif`) by [#pragma once](https://en.wikipedia.org/wiki/Pragma_once)
- Replace the method(using `#ifndef`, `#define`, `#endif`) by [#pragma once](https://en.wikipedia.org/wiki/Pragma_once)
- This pr will be merged after #145 are merged.
- modify in the same way header files added in #145 .
- Check if compilation succeeds.
- Compare `zen-desktop` binary size before and after change.
- run `zen-desktop -s weston-terminal` and it is performing broadly as expected.
=> replace #ifndef and #define by #pragma once

include/zen/scene/view.h, zen/scene/scene.c, zen/scene/view.c, zen/xwayland-view.c
Currently, the view is focused when clicked, but its order isn't changed.
Change the order of the view when the view is clicked.
1. start zen with more than two clients
2. click the view one by one
=> restack view

.github/workflows/lint.yaml, zen/xwayland-view.c
We have been using an unused format checker (editorconfig) in GitHub Actions.
Use clang-format for formatting check.
None
=> Clang Fromat Check

zen/scene/scene.c, zen/server.c
Send keyboard events to client
focus seat_keyboard to the view's surface
1. start zen with any client (reccomend: `weston-terminal`)
2. press any key (try also Tab or arrow key)
3. keyboard events will be sent
=> Send keyboard events

.clang-format, zen/cursor.c, zen/display-system.c, zen/input/input-manager.c, zen/input/seat.c, zen/scene/scene.c, zen/scene/screen-layout.c, zen/scene/screen.c, zen/screen-renderer.c, zen/xdg-toplevel-view.c
for coding experience.
Modified Clang-format settings to recognize some macros (`wl_list_for_each` etc) as foreach loops.
Just look at codes.
=> change clang-format config of foreach macros

zen/main.c, zen/scene/scene.c
At other DE, when press Ctrl+Alt+F1~, it switches to virtual terminal (tty).
Implement switching vt by `wlr_session_change_vt`
1. start zen
2. press Ctrl+Alt+F([1-9]|10)
3. switch to virtual terminal
=> add key binding for switching virtual terminal

include/zen/scene/scene.h, include/zen/scene/screen.h, include/zen/scene/view.h, include/zen/wlr/box.h, zen/cursor.c, zen/input/cursor-grab-move.c, zen/output.c, zen/scene/screen.c, zen/scene/view-child.c, zen/wlr/box.c, zen/xdg-toplevel-view.c, zen/xwayland-view.c
#116 ( before: #157 )
- return popup's surface by new `zn_screen_get_surface_at` function
The following behaviors can be checked with the Wayland clients (e.g., `vlc` `weston-terminal` `weston-flower`)
- When hovering over a menu item in the wayland client's popup menu, the color of the item changes.
- **In particular, it is possible to hover a popup outside the frame of the view.**
- When you click (button event) on each menu of the wayland client's popup, the input works accordingly (except unsupported functions such as minimize/maximize).
- **In particular, it is possible to click a popup outside the frame of the view.**
- After hiding a popup, input is sent to the view where the popup was (input is not sent to the popup).
- "hiding popup" should occur when...
- (right/left) click …
=> enable to input xdg popup

include/zen/cursor.h, include/zen/scene/scene.h, include/zen/server.h, zen/cursor.c, zen/main.c, zen/scene/scene.c, zen/server.c
See #167. And now, Segmentation Fault occurs when destroying texture.
destroy resources (e.g. client, backend, texture) before destroying server.
start zen and exit, check no error occured. Leave comments if you expect to destroy something before exiting.
=> [refactor] destroying process

.github/workflows/test.yaml, .gitignore, .gitmodules, meson.build, subprojects/remote-display-system.wrap
We used meson's wrap file to fetch [zen-remote-display-system](https://github.com/zigen-project/zen-remote-display-system). But it was hard to develop [zen-remote-display-system](https://github.com/zigen-project/zen-remote-display-system) and this repository at the same time. Using git submodules seems better in this situation.
Check that nothing about behavior have changed
=> use git submodules for remote display system

include/zen/immersive/display-system.h, include/zen/immersive/remote/display-system.h, include/zen/immersive/remote/object/board.h, include/zen/immersive/remote/renderer.h, include/zen/immersive/remote/scene.h, include/zen/immersive/renderer.h, include/zen/scene/board.h, include/zen/scene/scene.h, include/zen/server.h, zen/immersive/remote/display-system.c, zen/immersive/remote/object/board.c, zen/immersive/remote/renderer.c, zen/immersive/remote/scene.c, zen/input/pointer.c, zen/meson.build, zen/output.c, zen/scene/board.c, zen/scene/scene.c, zen/server.c
Introduce remote immersive display system
- switch display system using `cui-client`
- stop updating screen display system when using immersive display system
- stop cursor event when using immersive display system
- `remote-scene` consists of `remote-object`s
- `zn_board_remote_object` is the first `remote-object`
- `remote-scene` is basically mirror of `zn_scene`. `zn_scene` represents pure logic, and `remote-scene` constructs the information necessary for drawing, such as meshes, from the properties of `zn_scene`.
Any known unfinished work is left as TODO comments.
1. Build and run
2. Start `cui-client` and type "immersive". After that, the screen will not be updated and cursor will be unavailable.
3. During "immersive" display mode, the count of `zn_board` and `zn_board_remote_object` …
=> introduce remote display system

include/zen/input/cursor-grab-resize.h, include/zen/scene/view-child.h, include/zen/scene/view.h, zen/input/cursor-grab-move.c, zen/input/cursor-grab-resize.c, zen/scene/screen.c, zen/scene/view-child.c, zen/scene/view.c, zen/screen-renderer.c, zen/xdg-popup.c
See #147
Change meaning of view::x, y. It pointing to surface's pos before, but now `geometry` position.
Move the view to some position, check that there is no difference between specified pos and appeared pos.
[suggest] insert following line to `view.c:191` (at: `zn_view_map_to_scene`)
```c
zn_view_move(self, NULL, 0, 0);
```
=> change meaning of view's position

zen/scene/scene.c
#159 
It turned out that when you get underlying data from cairo rgb image [cairo converts the data into argb format](https://github.com/freedesktop/cairo/blob/923715f2e9acec31f6af406f39e14c36f9f7365c/src/cairo-png.c#L614) with `alpha = 0xff`. Using this, we can directly use RGB png image as the background image. 
Follow https://github.com/zigen-project/zen/pull/160#issue-1377382258 with a PNG image with RGB format.
=> Support RGB png for custom bg images

clients/box.cc, clients/gl-base-technique.cc, clients/gl-base-technique.h, clients/meson.build, clients/rendering-unit.h, zgnroot/include/zgnr/gl-base-technique.h, zgnroot/include/zgnr/gles-v32.h, zgnroot/meson.build, zgnroot/src/gl-base-technique.c, zgnroot/src/gl-base-technique.h, zgnroot/src/gles-v32.c, zgnroot/src/rendering-unit.h
Enable clients to create gl_base_technique.
Object is just created in zgnroot. Sending the object to the renderer is not the scope of this pull request.
=> implement creation of zgnr_gl_base_technique

zna/meson.build, zna/scene/virtual-object/gl-base-technique.c, zna/scene/virtual-object/gl-base-technique.h, zna/scene/virtual-object/rendering-unit.c, zna/scene/virtual-object/rendering-unit.h, zna/system.c, zna/system.h
Enable clients to create `zna_gl_base_technique`
Listen `zna_system::new_gl_base_technique` signal, create `zna_gl_base_technique`.
1. start zen / zen-oculus-display-system
2. launch `zen-box`; you can see the log `gl-base-technique is created`
3. terminate `zen-box`; the log `gl-base-technique is destroyed`
=> implement zna_gl-base-technique

clients/gl-base-technique.cc, clients/gl-base-technique.h, include/zen/renderer/gl-base-technique.h, meson.build, znr-remote/meson.build, znr-remote/src/gl-base-technique.cc, znr-remote/src/gl-base-technique.h
add gl base technique to zen renderer
added: `znr_gl_base technique` to `znr-remote`, `DrawArrays` to client's `GlBaseTechnique`.
(But now it can't be used)
none?
=> add znr_gl_base_technique

zna/system.c, zna/system.h
zna should have an ownership of the current session, but it's not.
=> make zna own current session

include/zen/renderer/gl-vertex-array.h, meson.build, zgnroot/include/zgnr/gles-v32.h, zgnroot/src/gles-v32.c, zna/meson.build, zna/scene/virtual-object/gl-base-technique.c, zna/scene/virtual-object/gl-buffer.c, zna/scene/virtual-object/gl-vertex-array.c, zna/scene/virtual-object/gl-vertex-array.h, zna/system.c, zna/system.h, znr-remote/meson.build, znr-remote/src/gl-vertex-array.cc, znr-remote/src/gl-vertex-array.h
Create vertex array object.
ref: https://github.com/zigen-project/zen-remote/pull/33
see https://github.com/zigen-project/zen-remote/pull/33
=> create vertex array object

zna/scene/virtual-object/gl-base-technique.c, zna/scene/virtual-object/gl-base-technique.h, zna/scene/virtual-object/gl-buffer.h
Start zen-box, GlBaseTechnique will be created in Quest.
When start zen-box, so much error log will be emitted. This will be fixed in another pull request in zen-remote.
=> Create znr_gl_base_technique on applying commit

include/zen/renderer/gl-vertex-array.h, meson.build, zgnroot/include/zgnr/gl-vertex-array.h, zgnroot/include/zgnr/gl-vertex-attrib.h, zgnroot/src/gl-vertex-array.c, zgnroot/src/gl-vertex-array.h, zgnroot/src/gl-vertex-attrib.c, zgnroot/src/gl-vertex-attrib.h, zna/scene/virtual-object/gl-vertex-array.c, znr-remote/src/gl-vertex-array.cc
Send vertex attributes to Quest using https://github.com/zigen-project/zen-remote/pull/37
You can check that the vertex attributes info is sent to Quest by output the vertex attributes info in Quest.
=> send vertex attributes info

clients/box.cc
Enable zen-box to use its own shaders and drawing method
See https://github.com/zigen-project/zen-remote/pull/48
=> enable zen-box to use own shaders and drawing method

include/zen/server.h, meson.build, zen/meson.build, zen/server.c, zna/meson.build, zna/system.c
Switch display system when renderer session starts
When Quest is connected, screen display poses.
`./build/zen/zen-desktop` moves to `./build/zen-desktop`
=> switch display system

include/zen/appearance/scene/ray.h, include/zen/scene/ray.h, zen/scene/ray.c, zen/scene/virtual-object.c, zgnroot/include/zgnr/mem-storage.h, zgnroot/src/gl-base-technique.c, zgnroot/src/mem-storage.c, zgnroot/src/mem-storage.h, zna/base-unit.c, zna/base-unit.h, zna/meson.build, zna/scene/ray.c, zna/scene/ray.h, zna/shader-inventory.c, zna/shader-inventory.h, zna/shaders/color.frag, zna/shaders/default.vert, zna/shaders/meson.build, zna/system.c, zna/system.h
So far we have been considering the case where the client application does the rendering. However, in this pull request, we will start treating "ray" as something that zen draws.
Start immersive display system
You will see a ray when a pointing device is connected. It will disappear when the pointing device is disconnected.
=> draw ray but without motion

.github/workflows/test.yaml, clients/box.cc, clients/default.vert, clients/gl-base-technique.cc, clients/gl-base-technique.h, clients/meson.build, include/zen/renderer/gl-base-technique.h, meson.build, zgnroot/include/zgnr/gl-base-technique.h, zgnroot/include/zgnr/gl-uniform-variable.h, zgnroot/meson.build, zgnroot/src/gl-base-technique.c, zgnroot/src/gl-base-technique.h, zgnroot/src/gl-uniform-variable.c, zgnroot/src/gl-uniform-variable.h, zna/scene/virtual-object/gl-base-technique.c, znr-remote/src/gl-base-technique.cc, znr-remote/src/session.cc
By enabling client to use uniform variable, together with frame request implemented in the previous pull request, clients can realize animation.
Start zen-box.
=> animation with uniform variable

zna/shaders/board.vert, zna/shaders/default.vert, zna/shaders/ray.vert, zna/shaders/view.vert
https://github.com/zigen-project/zen-remote/pull/59
change shader variable name `mvp` to 'zMVP`
=> change mvp name to zMVP

zna/base-unit.c
Previously, we used glGenTexImage but its not available in GLES.
Stop using glGetTexImage and use glReadPixel instead.
=> stop using glGenTexImage

.github/workflows/test.yaml
It taks too much time to build zen and other components which use grpc-dev.
Build time should be improved.
=> use prebuild grpc-dev to shorten the build time

include/zen/scene.h, include/zen/screen-layout.h, include/zen/screen.h, include/zen/wlr/box.h, zen/meson.build, zen/scene.c, zen/screen-layout.c, zen/screen.c, zen/screen/cursor-grab/default.c, zen/server.c, zen/wlr/box.c
See #249 
Re-introduce #72 (`zn_screen_layout`). limit the cursor's pos, move between screens.
1. start zen with multiple output (monitor)
2. move the cursor to the edge where outputs are adjacent; the cursor is moved to another output
3. try to move the cursor to outside of the output; it's not able
=> introduce screen layout

include/zen/board.h, include/zen/screen.h, include/zen/view.h, zen/board.c, zen/screen.c, zen/screen/output.c, zen/view.c
https://wayland.app/protocols/wayland#wl_surface:request:frame
https://wayland.app/protocols/wayland#wl_surface:request:damage
Run `weston-simple-egl` or `weston-simple-shm`
=> frame and view damage

zen/view.c, zna/board.c, zna/board.h
Enable animation in immersive display system
Start `weston-simple-egl`.
=> frame done event in immersive display system

include/zen/board.h, include/zen/cursor.h, include/zen/scene.h, include/zen/view.h, zen/board.c, zen/input/pointer.c, zen/scene.c, zen/screen/cursor-grab/default.c, zen/screen/xdg-toplevel.c, zen/view.c
Previous zen could send the cursor event to the client
Re-implement sending cursor event and focusing to the view
1. start zen
2. start some client with `WAYLAND_DEBUG=1`
3. move your input device
4. cursor event (such as `motion`, `frame`) will sent
=> send cursor event to the client

meson.build, znr-remote/src/session.cc
https://github.com/zigen-project/zen-remote/pull/61
Do not send frame done events to clients if network is busy.
Start several numbers of `weston-simple-egl`. 
FPS of each clients decreases.
Ray becomes heavy but not totally uncontrollable.
=> native congestion control

include/zen/cursor.h, include/zen/input/seat.h, include/zen/screen/cursor-grab/move.h, include/zen/screen/cursor-grab/resize.h, include/zen/screen/xdg-toplevel.h, include/zen/view.h, zen/cursor.c, zen/input/seat.c, zen/meson.build, zen/scene.c, zen/screen/cursor-grab/default.c, zen/screen/cursor-grab/move.c, zen/screen/cursor-grab/resize.c, zen/screen/xdg-toplevel.c, zen/view.c
implement changing the cursor texture, move / resize the view, rebase event
- 228ee3e8956b4877ec7edcdd9515fae89c62c9e5 : Listen set_cursor signal, update cursor texture when the client gives the cursor texture
- b5495d90b6bd35282c203c32c72ea2e072ba048b : make possible to move the view
- cdc1fbfe02b0b746ae9473a70d10759587a85c48 : make possible to resize the view
- ea14dd779d56657527a0be062aa35ed4ddf6e1bb : implement `rebase` to cursor grab
- fix bug that moving was not able when move had just finished
- ea14dd779d56657527a0be062aa35ed4ddf6e1bb : focus and restack the view
- a0383cfcf4a309305176f69f45b399e9d07fa28a : change initial view pos to center
1. start zen with some client - the view is at the center of the board, and focused
2. move cursor onto the client surface; the cursor is may …
=> move/resize by client-given cursor texture

include/zen/screen/xdg-toplevel.h, include/zen/view.h, zen/screen/cursor-grab/move.c, zen/screen/cursor-grab/resize.c, zen/screen/xdg-toplevel.c, zen/view.c
Implement maximizing alike other DE
handle maximize request
and, on c5c1828, the cursor names that used when resizing are changed.
1. start zen with some client
2. If you launch `weston-foobar`, the view has maximize button. When you press, the view is maximized
3. try to resize after maximizing - almost couldn't
4. try to move after maximizing - the view is unmaximized, and start moving
=> Maximize view by more-general cursor

include/zen/board.h, include/zen/config/config.h, include/zen/scene.h, include/zen/screen.h, zen/board.c, zen/config/config.c, zen/cursor.c, zen/scene.c, zen/screen.c, zen/screen/renderer.c, zen/server.c
Manage initial number of the board by config file. This PR make possible to place multiple board at Immersive Display System.
Add `board` table and `initial_count` key to config file.
(I incidentally fixed about issue about cursor texture at 7046285)
First, edit `~/.config/zen-desktop/config.toml` like following:
```toml
[board]
initial_count = 3
```
And start zen and remote display system. You can see the multiple board.
=> Add config about initial number of the board

include/zen/board.h, include/zen/view.h, zen/board.c, zen/screen/cursor-grab/default.c, zen/view.c
In now Immersive Display System, views' z position are same. But the order in the board should be taken into account.
Add `z_index` paramater to zn_view
Start zen with multiple client and remote client, and change the order of the view by clicking the view
=> introduce z-index to zn_view

include/zen/shell/shell.h, zen/scene.c, zns/seat-capsule.c, zns/seat-capsule.h, zns/shell.c
We can change the number of initial board, but they are overlapped.
Place board at the different pos on seat_capsule by `zns_seat_capsule_rearrange()`.
Edit `config.toml`, and start zen and with remote display system
=> set initial board pos

include/zen/peer.h, zen/peer.c, zen/remote.c, znr-remote/include/znr-remote.h, znr-remote/src/peer.cc
We want to get session information (ex: host name) from peer, but now the peer is destroyed when the connection is created.
Keep alive zn_peer, and give znr_session to zn_peer.
none
=> give znr_session to zn_peer

zigzag/src/node.c
https://github.com/zigen-project/zen/pull/295#discussion_r1063582636
In the current design, it is impossible to change the rendering & click region of a zigzag_node.
Updaed `zigzag_node_update_texture` so that the frame is reset every time the texture is updated. 
- Update `zn_power_set_frame` in `zen/ui/nodes/power-button.c` to assign `node->frame.y = rand() % 100`
- Confirm that position of the button changes every second.
=> Dynamically set frames of zigzag_node

zigzag/include/zigzag.h, zigzag/src/layout.c
FT_Face created from a FT_Library will be destroyed when the FT_Library is destroyed.
Destroying both results in double free.
ref: https://freetype.org/freetype2/docs/reference/ft2-base_interface.html#ft_library
Fix FT_Face destruction process.
=> fix FT_Face destruction

include/zen/server.h, zen/server.c, zen/ui/nodes/power-menu-item-logout.c
Handle unrecoverable failure.
Handle Unrecoverable failure.
Start zen without installing.
zen will exit soon with error message that says not asset found.
=> handle unrecoverable failure

common/cmd.c, common/include/zen-common.h, common/include/zen-common/cmd.h, common/meson.build, include/zen/config/config.h, include/zen/server.h, zen/config/config.c, zen/main.c, zen/server.c
We want to launch space app by default.
Add `space` table and `default_app` key to config file.
Edit your config file, and start zen. The app you specified will be launched automatically.
```toml
[space]
default_app = "zennist"
```
=> Add config about default space app

include/zen/screen.h, meson.build, zen/remote.c, zen/screen.c, zen/ui/zigzag-layout.c
Screen will not be damaged while in Immersive Display System.
But sometimes like vr_modal need to damage screen.
- add `zn_screen_damage_force`
With one Oculus Quest, try to connect via both wifi and adb port forward.
You can see two HMDs at first (wifi and adb port forward), but wifi's one will be disappear in few seconds.
=> Enable to damage screen in immersive display system for vr modal

zen/ui/zigzag-layout.c
#300
Make nodes intangible if any of the parents set `visible=false`
Click the area where "Logout" is supposed to appear and confirm that it does not trigger logout.
=> Make invisible nodes intangible

zen/ui/nodes/vr-modal/headset-dialog.c, zigzag/include/zigzag.h, zigzag/src/node.c
#299 
Updated the implementation  of `zigzag_node_update_texture`. Now, the caller needs to explicitly call `zigzag_node_update_frame` if it wants to change the position & size of the node.
Confirm that UI components (VR modal, power button... etc) work as expected.
=> Decoupled update_frame from update_texture

include/zen/cursor.h, include/zen/scene.h, zen/cursor.c, zen/scene.c
With current implementation, cursor is lost when switching to screen display system if the ray is not intersected with board then.
Rebase cursor when switching to SDS
Switching to SDS while the ray is not intersects with board.
=> Rebase cursor when switching to SDS

zgnroot/include/zgnr/gl-program.h, zgnroot/src/gl-program.c, zgnroot/src/gl-program.h, zna/virtual-object/gl-program.c
Resolve link problem when the same program is attached to multiple rendering units.
This PR solves the following problems.
- The same shader is linked many times.
- When connecting zen remote client, sometimes rendering unit is not rendered.
Multiple clients to attach the same program to multiple rendering units. (ex. zennist)
=> Fix program commit

include/zen/ui/nodes/app-launcher.h, include/zen/ui/nodes/vr-menu/connect-button.h, include/zen/ui/nodes/vr-menu/vr-menu.h, include/zen/ui/nodes/vr-modal/headset-dialog.h, zen/ui/nodes/app-launcher.c, zen/ui/nodes/menu-bar.c, zen/ui/nodes/power-button.c, zen/ui/nodes/power-menu/clock.c, zen/ui/nodes/power-menu/logout.c, zen/ui/nodes/power-menu/power-menu.c, zen/ui/nodes/vr-button.c, zen/ui/nodes/vr-menu/connect-button.c, zen/ui/nodes/vr-menu/headset.c, zen/ui/nodes/vr-menu/vr-menu.c, zen/ui/nodes/vr-modal/headset-dialog.c, zen/ui/nodes/vr-modal/vr-modal.c, zen/ui/zigzag-layout.c, zigzag/include/zigzag.h, zigzag/meson.build, zigzag/src/cairo_util.c, zigzag/src/layout.c, zigzag/src/node.c, zigzag/src/reconfigure.c
I do want something alike HTML flexbox
- Add `zigzag_cairo_draw_node_frame`
- Remove `zigzag_node_impl::set_frane`, introduce pending frame
- And also add `zigzag_node_add_child`, `zigzag_layout_add_node`
- `zigzag_node::texture` is created when the node is added to layout or other node
- Add `zigzag_node_reconfigure`
Use [watasuke102:test/refactor_zigzag](https://github.com/watasuke102/zen/tree/test/refactor-zigzag). Start zen on this branch, you can see some box. Click that, and they are reconfigured.
- I'll refactor `vr_modal` later (See #317)
- ~~This PR will open after merging #288 / #308 / #310 (maybe)~~
=> Refactor zigzag

meson.build
We need to bump the version of zen-remote to use `zModel`, `zView`, etc.
See https://github.com/zigen-project/zen-remote/pull/69.
Bump zen-remote version
=> bump zen-remote version

common/include/zen-common/util.h, zen/main.c
ref: https://github.com/zigen-project/zen/issues/322
Work around of https://github.com/zigen-project/zen/issues/322.
- The maximum number of files that can be opened was raised.
We need to solve the underlying problem.
=> unlimit file count

include/zen/appearance/system.h, zen/server.c, zna/system.c
We want to leave Immersive Display System by pressing Meta+V
Add keybind about leaving
Start zen, connect to zen-mirror, and press Meta+V
=> exit Immersive Display System by keybind

zen/ui/nodes/app-launcher.c
We can specify the icon of the app launcher by config, but only PNG image file was acceptable.
Try to render icon as SVG
Add app launcher item using SVG file as icon to config.
=> Use SVG icon at App Launcher

.github/workflows/test.yaml, meson.build, zen.desktop
Now we have a launcher, don't need startup shell
=> remove startup command

zen/ui/zigzag-layout.c
We can't focus to the view in Immersive Display System.
That happen because `zigzag` handle pointer button event. So ignore that if display system is Immersive.
Launch zen and zen-mirror, connect and start some client, clich them. The order of the view will be changed.
=> fix focusing on immersive

subprojects/packagefiles/glew/meson.build
With clang-15, zen fails to build GLEW like so.
```
../subprojects/glew-2.2.0/src/glew.c:10017:54: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
static GLboolean _glewInit_GL_AMD_draw_buffers_blend ();
^
void
../subprojects/glew-2.2.0/src/glew.c:10018:68: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
static GLboolean _glewInit_GL_AMD_framebuffer_multisample_advanced ();
^
void
../subprojects/glew-2.2.0/src/glew.c:10019:64: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
static GLboolean _glewInit_GL_AMD_framebuffer_sample_positions ();
^
void …
```
=> Enable to build glew with clang-15

common/include/zen-common/wlr/box.h, common/src/wlr/box.c, desktop/include/zen-desktop/cursor-grab.h, desktop/include/zen-desktop/shell.h, desktop/src/cursor-grab/default.c, desktop/src/screen.c, desktop/src/shell.c, test-harness/assert.c, test-harness/include/test-harness.h, zen/include/zen/cursor.h, zen/include/zen/seat.h, zen/include/zen/server.h, zen/include/zen/snode.h, zen/src/backend.h, zen/src/backend/backend.c, zen/src/backend/output.c, zen/src/backend/pointer.c, zen/src/backend/pointer.h, zen/src/backend/xwayland-surface.c, zen/src/cursor.c, zen/src/seat.c, zen/src/seat.h, zen/src/server.c, zen/src/snode.c, zen/tests/meson.build, zen/tests/server/construct-destroy.c, zen/tests/snode/snode-damage.c, zen/tests/snode/snode-frame.c, zen/tests/snode/snode-get-at.c, zen/tests/snode/snode-position.c
Enable to send pointer input to X clients
=> Pointer input

desktop/include/zen-desktop/ui/decoration.h, desktop/include/zen-desktop/ui/header-bar.h, desktop/include/zen-desktop/view.h, desktop/meson.build, desktop/src/ui/decoration.c, desktop/src/ui/header-bar.c, desktop/src/view.c, meson.build, zen/include/zen/snode.h, zen/include/zen/view.h, zen/src/backend/xwayland-surface.c, zen/src/backend/xwayland-surface.h, zen/src/snode.c, zen/src/view.c, zen/tests/snode/snode-get-at.c
Render decoration if needed to move views around.
Resizing is not the scope of this PR.
Move x apps.
=> Decoration
