- clients/include/zukou.h
- clients/simple-box/box.cc
- clients/simple-box/box.h
- clients/zukou/meson.build
- clients/zukou/opengl-component.cc
- clients/zukou/opengl-element-array-buffer.cc
- zen-renderer/opengl/meson.build
- zen-renderer/opengl/opengl-component.c
- zen-renderer/opengl/opengl-component.h
- zen-renderer/opengl/opengl-element-array-buffer.c
- zen-renderer/opengl/opengl-element-array-buffer.h
- zen-renderer/opengl/opengl.c
https://github.com/zigen-project/zigen/pull/12
↑これを使ってElement Array Buffer を使って描画できるようにした。
本当はVertex Buffer を複数の render component に attach する部分にプロトコル的に甘い部分がある。
> Element array buffer capability

- .github/workflows/test.yaml
- .gitignore
- README.adoc
- include/libzen-compositor/timespec-util.h
- include/zen-renderer/opengl-renderer.h
- include/zen-shell/zen-shell.h
- libzen-compositor/udev-seat.c
- meson.build
- meson_options.txt
- zen-backend/headless/output.c
- zen-backend/meson.build
- zen-backend/openvr/backend.cc
- zen-backend/openvr/gl-window.cc
- zen-backend/openvr/gl-window.h
- zen-backend/openvr/hmd.cc
- zen-backend/openvr/hmd.h
- zen-backend/openvr/meson.build
- zen-backend/openvr/output.cc
- zen-backend/openvr/output.h
- zen-renderer/opengl/opengl-component.c
- zen-renderer/opengl/opengl-renderer.c
- zen-renderer/opengl/ray-render-item.c
- zen/meson.build
openvr の backendを書いた。
glfwを用いたプレビューもあります。(というかglfwでcurrent context作らないとうまくいかなかった。windowとかを作らない空のcontextが作れるようなのってあるのだろうか。パッと探した感じ見つからなかった。)
> openvr backend

- .github/workflows/test.yaml
- clients/zpreview/app.cc
- clients/zpreview/app.h
- clients/zpreview/file-reader.cc
- clients/zpreview/file-reader.h
- clients/zpreview/http-reader.cc
- clients/zpreview/http-reader.h
- clients/zpreview/main.cc
- clients/zpreview/meson.build
- clients/zpreview/obj-object.cc
- clients/zpreview/obj-object.h
- clients/zpreview/obj-viewer.cc
- clients/zpreview/obj-viewer.h
- clients/zpreview/reader.h
- clients/zpreview/stl-object.cc
- clients/zpreview/stl-object.h
- clients/zpreview/stl-viewer.cc
- clients/zpreview/stl-viewer.h
- clients/zpreview/types.h
- meson.build
zpreview でobj ファイルを表示できるようにした。
obj ファイルなのに、マテリアルを読み込む部分とかを実装してないので、リッチな表示はできていない。
web 上のファイルもダウンロードして表示できるようにした。
> zpreview client: obj file feature

- clients/zukou/app.cc
- include/libzen-compositor/libzen-compositor.h
- libzen-compositor/data-device-manager.c
- libzen-compositor/data-device.c
- libzen-compositor/data-offer.c
- libzen-compositor/data-source.c
- libzen-compositor/drag-grab.c
- libzen-compositor/drag-grab.h
- libzen-compositor/ray.c
- libzen-compositor/seat.c
- zen-backend/glfw/backend.c
- zen-shell/cuboid-window.c
- zen/main.c
> Fix DnD focus and data_device management

- libzen-compositor/data-device.c
Fix https://github.com/zigen-project/zen/pull/23#discussion_r790208356
> Deal with the case resource of data_source is null

- libzen-compositor/data-device.c
> fix bug on delay dnd operation

- include/libzen-compositor/libzen-compositor.h
- zen-backend/openvr/hmd.cc
- zen-backend/openvr/hmd.h
- zen-backend/openvr/output.cc
- zen/main.c
単眼・狭視野のpreviewを表示できるようにした。
demo以外ではパフォーマンスを落とすし、たいして重要な機能ではないと思うのと、
サクッと実装してしまいたいので、demo branchにPRします。
> better demo preview

- include/libzen-compositor/libzen-compositor.h
- libzen-compositor/data-device.c
- libzen-compositor/drag-grab.c
- libzen-compositor/ray-client.c
- libzen-compositor/ray-client.h
- libzen-compositor/ray.c
- zen-renderer/opengl/ray-render-item.c
- zen-shell/desktop.c
https://github.com/zigen-project/zigen/pull/21
https://github.com/zigen-project/zigen/pull/23
↑ これらの実装
> ray length

- zen-renderer/opengl/ray-render-item.c
> set ray width 4

- clients/background-bathroom/main.cc
- clients/background-sky/field.cc
> Enable to render ocean with sky

- zen-renderer/opengl/opengl-shader-program.c
> close fd for shaders

- LICENSE
- meson.build
Suggestion to change LICENSE.
We need approves from the current license owners (@Aki-7(me), @shierote).
I approve this.
> Change LICENSE from Apache2.0 to MIT

- .github/workflows/test.yaml
- main.c
- meson.build
- src/main.c
- src/meson.build
- zen-util/include/zen-util.h
- zen-util/meson.build
- zen-util/src/log.c
- zen-util/src/meson.build
- setup wayland main loop
- add signal handler
> wayland main loop

- .github/workflows/test.yaml
- meson.build
- src/backend/drm/backend.c
- src/backend/drm/drm-props.c
- src/backend/drm/drm-props.h
- src/backend/drm/kms-crtc.c
- src/backend/drm/kms-crtc.h
- src/backend/drm/kms-head.c
- src/backend/drm/kms-head.h
- src/backend/drm/kms-plane.c
- src/backend/drm/kms-plane.h
- src/backend/drm/kms.c
- src/backend/drm/kms.h
- src/backend/drm/meson.build
- find gpu(drm) device to use.
- kms object skeleton
- check several capabilities which seem necessary
- kms crtc object skeleton
- initialize KMS crtc object
- initialize KMS plane object
- kms head (connector) skeleton
> find primary gpu

- .github/workflows/test.yaml
- meson.build
- meson_options.txt
- protocols/meson.build
- protocols/zen-desktop.xml
- tests/meson.build
- tests/protocol/validate-xml-test.c
- tests/test-runner.c
- tests/test-runner.h
- tests/validate-xml-test.c
- Create a tentative protocol to switch desktop modes
- Add test code to validate protocol xml
> create a tentative protocol to switch desktop modes

- .github/PULL_REQUEST_TEMPLATE/new_feature.md
Little by little, each developer started doing different tasks. I know you are busy with your own development, but I think it is important to catch up with what other developers are developing. So I'm going to set up a section in the pull request so that other people can easily check the new behavior you made. What do you think?
Inspired by #75. 
#76 is an example.
> Add template for new feature pull request

- .github/PULL_REQUEST_TEMPLATE/new_feature.md
apply #77 to main
Added a pull request template to dev branch in #77, but it seem that a pull request template won't work unless we add it to main branch.
So I added to main.
> add pr template; How to check behavior section

- include/zen/server.h
- zen/output.c
- zen/server.c
- zen/xdg-toplevel-view.c
- zen/xwayland-view.c
make zn_server struct public.
No behavior changed
> make zn_server struct public

- include/zen/output.h
- include/zen/scene/scene.h
- include/zen/scene/screen-layout.h
- include/zen/scene/screen.h
- zen/meson.build
- zen/output.c
- zen/scene/scene.c
- zen/scene/screen-layout.c
- zen/scene/screen.c
- zen/xdg-toplevel-view.c
- zen/xwayland-view.c
add screen layout, and screens are now owned by zn_screen_layout instead of zn_scene.
zn_scene -> zn_screen_layout -> zn_screen (wl_list)
> add zn_screen_layout

- include/zen/cursor.h
- include/zen/input-manager.h
- include/zen/scene/screen-layout.h
- include/zen/scene/screen.h
- include/zen/seat.h
- zen/cursor.c
- zen/input-manager.c
- zen/meson.build
- zen/render-2d.c
- zen/scene/screen-layout.c
- zen/scene/screen.c
- zen/seat.c
- zen/server.c
implement a part of #89 
The cursor is just shown on center of the screen. Cannot move.
1. start zen
2. appear the cursor on center of the screen
> add zn_cursor

- zen/server.c
fix https://github.com/zigen-project/zen/issues/82.
- To use x client in startup command (or `-s` option), xwayland is started with lazy option in `zn_server_create` instead of `zn_server_run`.
- Some corrections, including mistakes that destructor is not written.
```
$ zen-desktop -s xeyes
```
Then, the monitor shows xeyes's window.
Without this pr, this command terminates zen-desktop without showing any windows.
> Change the timing of creating and starting xwayland with lazy option

- zen/scene/view.c
Follow-up PR of #146. 
Fix the weird reference in #146.
Same as the process in #146.
> Remove the weird reference

- include/zen/input/cursor-grab-resize.h
- include/zen/scene/view.h
- include/zen/xdg-toplevel-view.h
- include/zen/xwayland-view.h
- zen/input/cursor-grab-resize.c
- zen/meson.build
- zen/scene/view.c
- zen/xdg-toplevel-view.c
- zen/xwayland-view.c
Resize the view by the cursor.
Add `zn_cursor_grab_resize`.
1. start zen and some wayland client
2. drag the corner of the view
3. the size of the view is changed following the cursor
> resize view

- zen/xdg-toplevel-view.c
In #156 (2123ebe), I forgot to remove debug message.
remove
none
> remove unnecessary debug message

- common/include/zen-common.h
- common/include/zen-common/terminate.h
- common/meson.build
- common/terminate.c
- meson.build
- zen/backend/remote/immersive-backend.cc
- zen/backend/remote/loop.cc
- zen/backend/remote/loop.h
- zen/backend/remote/meson.build
- zen/main.c
See: https://github.com/zigen-project/zen-remote-display-system/pull/3
See: https://github.com/zigen-project/zen-remote-display-system/pull/3
CI should pass when https://github.com/zigen-project/zen-remote-display-system/pull/3 is merged.
> find peer node using UDP broadcast

- .gitignore
- .gitmodules
- common/include/zen-common/log.h
- include/zen/immersive/remote/display-system.h
- meson.build
- zen/immersive/remote/display-system.c
- zen/meson.build
- znr/include/znr/log.h
- znr/include/znr/remote.h
- znr/meson.build
- znr/src/log.cc
- znr/src/loop.cc
- znr/src/loop.h
- znr/src/remote.cc
Apply https://github.com/zigen-project/zen-remote-display-system/pull/4
See https://github.com/zigen-project/zen-remote-display-system/pull/4.
Apply https://github.com/zigen-project/zen-remote-display-system/pull/5
Apply https://github.com/zigen-project/zen-remote-display-system/pull/5
Nothing
> introduce zen-remote

- .github/workflows/test.yaml
- .gitmodules
- README.adoc
- meson.build
apply https://github.com/zigen-project/zen-remote/pull/7
apply https://github.com/zigen-project/zen-remote/pull/7
Build it following the instruction at README
> use zen-remote as normal dependency

- include/zen/immersive/remote/object/ray.h
- meson.build
- zen/immersive/remote/object/ray.c
- znr/include/znr/gl-buffer.h
- znr/include/znr/rendering-unit.h
- znr/include/znr/virtual-object.h
- znr/meson.build
- znr/src/gl-buffer.cc
- znr/src/gl-buffer.h
- znr/src/rendering-unit.cc
- znr/src/virtual-object.cc
- znr/src/virtual-object.h
https://github.com/zigen-project/zen-remote/pull/15
See https://github.com/zigen-project/zen-remote/pull/15.
CI should pass after https://github.com/zigen-project/zen-remote/pull/15 is merged
> apply https://github.com/zigen-project/zen-remote/pull/15

- include/zen/immersive/remote/object/ray.h
- include/zen/scene/ray.h
- meson.build
- zen/immersive/remote/object/ray.c
- zen/input/pointer.c
- zen/scene/ray.c
- znr/include/znr/buffer.h
- znr/include/znr/gl-buffer.h
- znr/meson.build
- znr/src/buffer.cc
- znr/src/buffer.h
- znr/src/gl-buffer.cc
- znr/src/remote.cc
- znr/src/rendering-unit.cc
- znr/src/virtual-object.cc
https://github.com/zigen-project/zen-remote/pull/16
See https://github.com/zigen-project/zen-remote/pull/16
CI should pass after https://github.com/zigen-project/zen-remote/pull/16 is merged
> apply https://github.com/zigen-project/zen-remote/pull/16

- meson.build
- zen/immersive/remote/object/ray.c
- zen/input/pointer.c
- znr/include/znr/gl-buffer.h
- znr/src/gl-buffer.cc
https://github.com/zigen-project/zen-remote/pull/21
apply https://github.com/zigen-project/zen-remote/pull/21
See https://github.com/zigen-project/zen-remote/pull/21
- CI should pass after https://github.com/zigen-project/zen-remote/pull/21 is merged
> apply https://github.com/zigen-project/zen-remote/pull/21

- clients/box.cc
- clients/gl-buffer.cc
- clients/gl-buffer.h
- clients/meson.build
- include/zen/renderer/gl-buffer.h
- include/zen/renderer/rendering-unit.h
- zgnroot/include/zgnr/gl-buffer.h
- zgnroot/include/zgnr/gles-v32.h
- zgnroot/meson.build
- zgnroot/src/compositor.c
- zgnroot/src/gl-base-technique.c
- zgnroot/src/gl-buffer.c
- zgnroot/src/gl-buffer.h
- zgnroot/src/gles-v32.c
- zgnroot/src/rendering-unit.c
- zgnroot/src/virtual-object.c
- zna/meson.build
- zna/scene/virtual-object/gl-buffer.c
- zna/scene/virtual-object/gl-buffer.h
- zna/scene/virtual-object/rendering-unit.c
- zna/system.c
- zna/system.h
- znr-remote/meson.build
- znr-remote/src/gl-buffer.cc
- znr-remote/src/gl-buffer.h
Enable clients to create glBuffer
Run zen-box and see the log. Nothing more we can check the behavior so far.
> enable to create gl buffer

- zgnroot/src/gl-vertex-attrib.c
- zna/scene/virtual-object/gl-base-technique.c
- zna/scene/virtual-object/gl-buffer.c
- zna/scene/virtual-object/gl-buffer.h
add apply-commit method for zna_gl_buffer.
> apply gl-buffer commit

- clients/box.cc
- include/zen/renderer/gl-base-technique.h
- meson.build
- zgnroot/include/zgnr/gl-base-technique.h
- zgnroot/src/gl-base-technique.c
- zgnroot/src/gl-base-technique.h
- zna/scene/virtual-object/gl-base-technique.c
- znr-remote/src/gl-base-technique.cc
https://github.com/zigen-project/zen-remote/pull/38
Bind vertex array to gl_base_technique
> use https://github.com/zigen-project/zen-remote/pull/38 to bind vertex array

- include/zen/renderer/gl-base-technique.h
- zgnroot/include/zgnr/gl-base-technique.h
- zgnroot/src/gl-base-technique.c
- zgnroot/src/gl-base-technique.h
- zna/scene/virtual-object/gl-base-technique.c
- znr-remote/src/gl-base-technique.cc
continued from #206 
add znr_gl_base_technique_draw_arrays, send information about draw method
none
**This PR is based on #213**
> add znr_gl_base_technique_draw_arrays

- clients/box.cc
- clients/gl-program.cc
- clients/gl-program.h
- clients/meson.build
- include/zen/renderer/gl-program.h
- meson.build
- zgnroot/include/zgnr/gl-program.h
- zgnroot/include/zgnr/gles-v32.h
- zgnroot/meson.build
- zgnroot/src/gl-program.c
- zgnroot/src/gl-program.h
- zgnroot/src/gles-v32.c
- zna/meson.build
- zna/scene/virtual-object/gl-program.c
- zna/scene/virtual-object/gl-program.h
- zna/system.c
- zna/system.h
- znr-remote/meson.build
- znr-remote/src/gl-program.cc
- znr-remote/src/gl-program.h
Enable to create and destroy gl-program
Nothing we can do yet
> enable to create and destroy gl-program

- clients/box.cc
- clients/gl-base-technique.cc
- clients/gl-base-technique.h
- include/zen/renderer/gl-base-technique.h
- meson.build
- zgnroot/include/zgnr/gl-base-technique.h
- zgnroot/src/gl-base-technique.c
- zgnroot/src/gl-base-technique.h
- zgnroot/src/gl-program.c
- zgnroot/src/gl-program.h
- zna/scene/virtual-object/gl-base-technique.c
- znr-remote/src/gl-base-technique.cc
Enable to bind glProgram to glBaseTechnique
No thing you can do yet.
> enable to bind gl-program to base technique

- clients/box.cc
- clients/color.frag
- clients/default.vert
- clients/gl-program.cc
- clients/gl-program.h
- clients/gl-shader.cc
- clients/gl-shader.h
- clients/meson.build
- include/zen/renderer/gl-program.h
- meson.build
- zgnroot/include/zgnr/gl-program.h
- zgnroot/include/zgnr/program-shader.h
- zgnroot/meson.build
- zgnroot/src/gl-program.c
- zgnroot/src/gl-program.h
- zgnroot/src/program-shader.c
- zgnroot/src/program-shader.h
- zna/scene/virtual-object/gl-program.c
- znr-remote/src/gl-program.cc
attach and link shaders
Nothing yet
> attach and link shaders

- clients/application.cc
- clients/application.h
- clients/bounded.cc
- clients/bounded.h
- clients/box.cc
- clients/meson.build
- clients/virtual-object.cc
- clients/virtual-object.h
- doc/structure.adoc
- include/zen/server.h
- include/zen/shell/shell.h
- meson.build
- protocols/meson.build
- zen/server.c
- zgnroot/include/zgnr/bounded.h
- zgnroot/include/zgnr/shell.h
- zgnroot/meson.build
- zgnroot/src/bounded.c
- zgnroot/src/bounded.h
- zgnroot/src/shell.c
- zgnroot/src/shell.h
- zns/bounded.c
- zns/bounded.h
- zns/meson.build
- zns/shell.c
- zns/shell.h
Create a component to realize interactive 3D GUI shell.
1 Run zen-box. In log, you can confirm that the zgn_bounded is created
> add zn_shell

- include/zen/renderer/virtual-object.h
- meson.build
- znr-remote/src/virtual-object.cc
https://github.com/zigen-project/zen-remote/pull/52
add znr_virtual_object_move
Modify code and use it.
> virtual object move [znr-remote]

- clients/bounded.cc
- clients/bounded.h
- clients/box.cc
- include/zen/ray.h
- include/zen/scene/virtual-object.h
- zen/input/pointer.c
- zen/ray.c
- zen/scene/virtual-object.c
- zgnroot/include/zgnr/bounded.h
- zgnroot/include/zgnr/seat.h
- zgnroot/src/bounded.c
- zgnroot/src/seat.c
- zna/scene/virtual-object.c
- zna/scene/virtual-object.h
- zns/bounded.c
- zns/bounded.h
- zns/meson.build
- zns/ray-grab/default.c
- zns/ray-grab/default.h
- zns/ray-grab/move.c
- zns/ray-grab/move.h
Move Virtual Object
Start zen-box, you can move them
> Move virtual object.

- .github/workflows/test.yaml
We are developing in `dev` branch.
Enable CI test in dev branch.
> add ci test for dev branch

- .github/workflows/lint.yaml
> add lint check for dev branch

- .github/workflows/test.yaml
- README.adoc
- include/zen/scene.h
- include/zen/server.h
- include/zen/space.h
- meson.build
- protocols/meson.build
- zen/meson.build
- zen/scene.c
- zen/server.c
- zen/space.c
- zen/virtual-object.c
- zgnroot/include/zgnr/space-manager.h
- zgnroot/include/zgnr/space.h
- zgnroot/meson.build
- zgnroot/src/bounded.c
- zgnroot/src/space-manager.c
- zgnroot/src/space-manager.h
- zgnroot/src/space.c
- zgnroot/src/space.h
- zns/shell.c
https://github.com/zigen-project/zen-protocols/pull/3
Enable to show space using https://github.com/zigen-project/zen-protocols/pull/3
See TBD
> enable to show space

- include/zen/cursor.h
- include/zen/shell/shell.h
- zen/screen/cursor-grab/default.c
- zen/server.c
- zns/board.c
- zns/shell.c
zen-desktop hangs on termination.
Fix the issue.
zen-desktop will not hang on termination.
> fix hang on termination

- zgnroot/include/zgnr/bounded.h
- zgnroot/src/bounded.c
- zgnroot/src/bounded.h
- zns/bounded.c
- zns/bounded.h
- zns/meson.build
- zns/ray-grab/move.c
- zns/seat-capsule.c
- zns/seat-capsule.h
- zns/shell.c
- zns/shell.h
Introduce seat capsule.
Move bounded object, for example zukou-box.
> introduce seat capsule

- include/zen/board.h
- include/zen/cursor.h
- include/zen/view.h
- zen/board.c
- zen/cursor.c
- zen/view.c
- zna/board/plane-unit.c
- zna/cursor.c
- zna/view.c
- zns/board.c
- zns/board.h
- zns/ray-grab/board-move.c
- zns/ray-grab/board-move.h
- zns/ray-grab/move.c
- zns/seat-capsule.c
- zns/seat-capsule.h
- zns/shell.c
Move board on seat capsule
Move board on seat capsule
Move board!
> move board on seat capsule

- include/zen/view.h
- zen/screen/xdg-toplevel.c
- zen/view.c
See #174 
re-inplement of #174
Start zen with some client, make sure that the left-top of the view is ajacent to the left-top of the output
> add window_geom

- zen/screen/cursor-grab/default.c
- zns/board.c
Pointer events in immersive display system.
Send enter / motion / leave / button events to wayland client.
start `weston-clickdot` in immersive display system
> Pointer events in IDS

- common/include/zen-common.h
- common/include/zen-common/signal.h
- common/meson.build
- common/signal.c
- zen/board.c
- zen/ray.c
- zgnroot/include/zgnr/seat.h
- zgnroot/src/seat.c
- zgnroot/src/seat.h
- zns/board.c
- zns/bounded.c
- zns/meson.build
- zns/node.c
- zns/node.h
- zns/ray-grab/board-move.c
- zns/ray-grab/board-move.h
- zns/ray-grab/default.c
- zns/ray-grab/default.h
- zns/ray-grab/down.c
- zns/ray-grab/down.h
- zns/ray-grab/move.c
- zns/ray-grab/move.h
- zns/shell.c
- zns/shell.h
ray's down grab
1. Start zukou-box
2. Click inner box with "right" button
3. move around the ray without releasing
4. inner box stays pink color
5. release the button, and the color get back to red.
> ray down grab

- include/zen/cursor.h
- include/zen/view.h
- zen/cursor.c
- zen/scene.c
- zen/screen/cursor-grab/default.c
- zen/screen/cursor-grab/down.c
- zen/screen/cursor-grab/move.c
- zen/screen/cursor-grab/resize.c
- zen/view.c
- zns/board.c
- zns/ray-grab/board-move.c
Move view in immersive display system.
Move view in immersive display system.
> move view in immersive display system

- zen/scene.c
re-implement #161
focus seat_keyboard to the view's surface
1. start zen with any client (reccomend: `weston-terminal`)
2. press any key (try also: Tab, arrow key, C-u, etc)
3. keyboard events will be sent
> Send keyboard events

- include/zen/ui/nodes/menu-bar.h
- include/zen/ui/nodes/power-button.h
- include/zen/ui/nodes/power-menu-item-clock.h
- include/zen/ui/nodes/power-menu-item-logout.h
- include/zen/ui/nodes/power-menu.h
- include/zen/ui/zigzag-layout.h
- zen/meson.build
- zen/screen/cursor-grab/default.c
- zen/screen/renderer.c
- zen/ui/nodes/menu-bar.c
- zen/ui/nodes/power-button.c
- zen/ui/nodes/power-menu-item-clock.c
- zen/ui/nodes/power-menu-item-logout.c
- zen/ui/nodes/power-menu.c
- zen/ui/zigzag-layout.c
- zigzag/include/zigzag.h
- zigzag/src/cairo_util.c
- zigzag/src/node.c
Add menu items above the power button and show/hide it with click. 
- Click the power button on the bottom-right corner and confirm that the power menu shows up
- Click "Logout" and confirm that the server gracefully exits.
> Add power menu (logout)

- zgnroot/include/zgnr/expansive.h
- zgnroot/src/expansive.c
- zgnroot/src/expansive.h
- zns/bounded.c
- zns/expansive.c
- zns/expansive.h
Collision region is required in expansive 3D window.
- Handle zgn_expansive::set_region
> region for expansive

- zna/view.c
Generate and use mipmap for views.
Generate and use mipmap for views.
> enable mipmap for view

- include/zen/peer.h
- zen/peer.c
- zen/ui/nodes/vr-modal/headset-dialog.c
- znr-remote/include/znr-remote.h
- znr-remote/src/peer.cc
Fix design of VR modal
- increase vertical margin of the dialog
- show "Wired" text instead of hostname
Start zen and quest.
> Fix VR modal design

- .github/workflows/lint.yaml
- .github/workflows/test.yaml
- .gitignore
- 3rd-party/meson.build
- 3rd-party/tomlc99/README
- 3rd-party/tomlc99/include/toml.h
- 3rd-party/tomlc99/meson.build
- 3rd-party/tomlc99/toml.c
- README.adoc
- include/zen/wlr/render/egl.h
- include/zen/wlr/render/glew.h
- meson.build
- subprojects/glew.wrap
- subprojects/packagefiles/glew/meson.build
- zen/meson.build
- zen/server.c
- zen/wlr/render/egl.c
- zen/wlr/render/glew.h
- zen/wlr/render/pixel_format.c
- zen/wlr/render/renderer.c
- zen/wlr/render/shaders.c
- zen/wlr/render/texture.c
- zna/base-unit.c
Simplify dependencies.
- Use apt to install cglm
- Include tomlc99 source file into this project.
> simplify dependencies

- zns/include/zns/node.h
- zns/src/board.c
- zns/src/bounded-nameplate.c
- zns/src/bounded.c
- zns/src/expansive.c
- zns/src/node.c
- zns/src/ray-grab/down.c
- zns/src/shell.c
> move view between boards in ids

- .github/workflows/test.yaml
https://github.com/zwin-project/zen/pull/344
Add CI test building with clang-15
Check that the CI passes
> Add test for clang-15

- meson.build
Prepare release v0.1.1
Update version
> Prepare release 0.1.1

- meson.build
Prepare for release 0.1.2
Update version
> Prepare release 0.1.2

- meson.build
Prepare for the next development iteration
Update version
> Prepare for next development iteration

- .gitignore
- README.adoc
#226 
Update README mentioning that we only support clang.
> Update README (clang)

- README.adoc
- doc/CONTRIBUTING.adoc
Add contributing guide. The content is not fully filled yet.
Add a contributing page.
> Add contributing guide

- doc/BUILD.adoc
- doc/CONTRIBUTING.adoc
The first step in contributing to zen is to build zen from source.
Add a guide to building zen from source.
> Add build guide

- doc/BUILD.adoc
Add note about missing packages.
> Add note about missing packages

- desktop/include/zen-desktop/screen-container.h
- desktop/include/zen-desktop/screen-layout.h
- desktop/include/zen-desktop/shell.h
- desktop/meson.build
- desktop/src/screen-container.c
- desktop/src/screen-layout.c
- desktop/src/shell.c
- desktop/tests/meson.build
- desktop/tests/screen-layout/layout.c
- doc/dev/coordinates.adoc
- zen/include/zen/cursor.h
- zen/include/zen/screen.h
- zen/include/zen/seat.h
- zen/src/backend/output.c
- zen/src/backend/output.h
- zen/src/backend/pointer.c
- zen/src/cursor.c
- zen/src/cursor.h
- zen/src/screen.c
- zen/src/seat.c
- zen/src/snode.c
- zen/tests/mock/include/mock/output.h
- zen/tests/mock/src/backend.c
- zen/tests/mock/src/output.c
- zen/tests/snode/snode-damage.c
Screen layout handles the positional relationship among screens.
No thing to check yet. Only tests show behavior.
> introduce screen layout

- desktop/include/zen-desktop/cursor-grab.h
- desktop/include/zen-desktop/cursor-grab/move.h
- desktop/include/zen-desktop/shell.h
- desktop/include/zen-desktop/view.h
- desktop/meson.build
- desktop/src/cursor-grab.c
- desktop/src/cursor-grab/default.c
- desktop/src/cursor-grab/move.c
- desktop/src/screen.c
- desktop/src/shell.c
- desktop/src/view.c
- zen/include/zen/config.h
- zen/include/zen/snode.h
- zen/include/zen/view.h
- zen/src/backend/xwayland-surface.c
- zen/src/backend/xwayland-surface.h
- zen/src/snode.c
- zen/src/view.c
Enable to move CSD application.
Now you can move around google chrome.
> create desktop view

- .clang-tidy
- desktop/src/screen.c
- meson.build
- protocol/meson.build
- protocol/wlr-layer-shell-unstable-v1.xml
- zen/include/zen/screen.h
- zen/include/zen/seat.h
- zen/src/backend/backend.c
- zen/src/backend/compositor.c
- zen/src/backend/compositor.h
- zen/src/backend/layer-surface.c
- zen/src/backend/layer-surface.h
- zen/src/backend/meson.build
- zen/src/backend/output.c
- zen/src/backend/output.h
- zen/src/backend/screen-backend.c
- zen/src/backend/screen-backend.h
- zen/src/screen.c
- zen/src/seat.c
- zen/tests/mock/include/mock/output.h
- zen/tests/mock/src/output.c
wlr_layer_shell is a protocol for creating system widgets like a menu bar.
We will not include an app launcher and such system widgets in zen, but the zennist will implement them.
Implement wlr_layer_shell.
leave #388 #389 
Try this zennist!
https://github.com/zwin-project/zennist/tree/v0.2.0-dev
You can see the wallpaper drawn by the zennist.
> Layer shell
